require('impatient').enable_profile()

require('plugins')
require('options')
require('keymaps')
-- require('themes.onedark')
require('themes.gruvbox')
-- require('themes.onedark')
-- require('themes.github')
require('util')
